Full screen post
slmbakkenes/RampUpSocialMediaApp pull request #29
Opened 2024-10-09 10:19 UTC by Winterwolf365

2024-10-09 16:34 UTC, WaterNinja05 requested changes

2024-10-09 16:34 UTC, WaterNinja05 commented on templates/index.html
Vraagje, waarom doe je de onclick om de image en h2 van de caption? Je zou hem op de hele post kunnen doen, anders eventueel op de div die de image en h2 bevatten. Dat is een stuk mooier zegmaar.

2024-10-09 16:34 UTC, WaterNinja05 commented on templates/index.html
>                  <div class="basis-1/2 h-full flex flex-col md:mr-4">
Dus in deze div als zou je niet de hele post doen

2024-10-09 16:34 UTC, WaterNinja05 commented on templates/index.html
> +        <a class="border-4 border-gray-400 z-10 bg-gray-50 p-4 my-4 flex flex-col md:aspect-video rounded-lg shadow hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
Maak anders van deze Anchor tag een div en voeg een onclick toe.

2024-10-09 16:34 UTC, WaterNinja05 commented on templates/Post/post_detail.html
> +        <div class="h-full flex flex-col md:ml-4 overflow-y-auto object-scale-down md:max-h-full max-h-48"
Waarom zet je de comments buiten de Post card? Het ziet er nu een beetje raar uit daardoor... Ook omdat de image nog steeds maar de helft van de kaart opneemt. Ik zie dat de comments section buiten de anchor tag staat, dus mogelijk is het daar fout gegaan. Kijk ook even of het er logisch en mooi uit ziet, dan voorkom je dubbel werk!

2024-10-09 16:34 UTC, WaterNinja05 commented on templates/index.html
Het is nu ook raar met de like functie, aangezien je daar niet kan klikken dus je moet specifiek ergens klikken, laat duidelijk zien aan de gebruiker waar dat dan is!

2024-10-09 19:26 UTC, Winterwolf365 commented on templates/index.html
ik snap niet percies wat je over de like functie zegt, door alleen de image en h2 te gebruiken behoud je juist de like functionalitied en ga je niet naar de detail pagina als je op de like drukt. En de reden dat ik dat dus gedaan had is omdat je anders als je op de like of profiel klikt niet dat te zien krijgt maar naar de detail pagina gaat. Dit leek mij de meest lochise oplossing om de like en porfiel knoppen functionaliteit te behouden.

2024-10-09 19:32 UTC, Winterwolf365 commented on templates/Post/post_detail.html
> +        <div class="h-full flex flex-col md:ml-4 overflow-y-auto object-scale-down md:max-h-full max-h-48"
De image neemt de hele ruimte op niet alleen de helft zoals op de home pagina, en ik had de comment erbuiten gezet omdat ik zerf dacht dat dat mooier zou zijn (omdat je dan niet alleen 1 card op een pagina heb maar meerder onderdelen), en dat je dan wat anders heb dan op de home pagina, en het is wel duidelijk dat de comments van de posts zijn omdat het maar 1 post op de pagina is. Maar ik kan dat nog niet testen dus ik weet nog niet hoe de comment er zo uit zien, maar als jij het mooier daarin vind kan ik dat ook prima doen, mij maakt het niet veel uit maar dat was de reden waarom ik het had gedaan op deze manier.

2024-10-16 07:43 UTC, Winterwolf365 commented on templates/index.html
@WaterNinja05 wat denk je dan wat nu het slimst is om te doen hier?

2024-10-16 07:45 UTC, Winterwolf365 commented on templates/Post/post_detail.html
> +        <div class="h-full flex flex-col md:ml-4 overflow-y-auto object-scale-down md:max-h-full max-h-48"
@WaterNinja05 Zal ik comment oneraan binnen de card zetten?

2024-10-16 07:48 UTC, WaterNinja05 requested changes
Er is niks verandert sinds de vorige keer qua full screen post, alleen main is erin gemerged

2024-10-16 08:06 UTC, Winterwolf365 commented
> Er is niks verandert sinds de vorige keer qua full screen post, alleen main is erin gemerged

Dat komt omdat ik omdat ik niet percies wist wat er moest gebeuren, zal ik de link op de h2 img zo laten omdat daar niet een makkelijke andere oplossing is, en de comments binnen de card onderaan zetten?

2024-10-16 17:50 UTC, merged